---
dependencies:
  - role: ensure-default-user
    vars:
      user: zaci
  - role: staticdev.pyenv
    vars:
      pyenv_env: "user"
      pyenv_version: "v2.4.5"
      pyenv_path: "/home/zaci/.pyenv"
      pyenv_owner: zaci
      pyenv_shellrc_file: /home/zaci/.bashrc
      pyenv_virtualenv_version: "v1.2.3"
      pyenv_enable_autocompletion: true
      pyenv_python_versions:
        - 3.10.14
      pyenv_global:
        - 3.10.14
      pyenv_python_configure_opts: --enable-optimizations --with-lto --enable-shared
      pyenv_virtualenvs:
        - venv_name: psychopy_session_webserver
          py_version: 3.10.14
      pyenv_make_opts: "-j4"
