---
- name: ensure vertigo account is set
  user:
    name: vertigo
    comment: Vertigo Main Account
    groups:
      - sudo
    append: yes
    password: "{{ vertigo_password }}"

- name: check boot options
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: "^(#)?autologin-user=.*"
    line: "autologin-user=vertigo"
  check_mode: true
  register: vertigo_autologin

- name: set boot behavior to desktop autologin vertigo
  shell: |
    env SUDO_USER=vertigo raspi-config nonint do_boot_behaviour "B4 Desktop Autologin"
  when: vertigo_autologin.changed
