---

- name: install required packages
  apt:
    name:
      - libhidapi-hidraw0
      - qt6-base-dev
      - qtchooser
      - libgtk-3-dev
      - libgtk-4-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libglut-dev
      - libwebkit2gtk-4.0-dev
      - libwebkitgtk-6.0-dev
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
      - libsdl2-dev
      - libnotify-dev
      - libsm-dev
    state: present

- name: adds support for qt6 to qtchooser
  copy:
    src: qt6.conf
    dest: /usr/share/qtchooser/qt6.conf

- name: sets qt6 as default
  file:
    path: /usr/lib/aarch64-linux-gnu/qt-default/qtchooser
    src: /usr/share/qtchooser/qt6.conf
    state: link

- name: copy pre-compiled wheels
  synchronize:
    src: wheels/
    dest: /usr/local/wheels/
    rsync_opts:
      - '--include=*.whl'
      - '--exclude=*'

- name: install psychopy_session_webserver
  become_user: zaci
  become: yes
  pip:
    extra_args: --upgrade -f /usr/local/wheels
    name:
      - pip
      - psychopy==2024.1.4
      - unil-pellet-dispenser
      - psychopy-zaci
      - git+https://github.com/atuleu/zaci#egg=psychopy-session-webserver&subdirectory=psychopy-session-webserver

    virtualenv: /home/zaci/psychopy/venv
    virtualenv_command: /home/zaci/.pyenv/shims/python -m venv
