---

- name: install required packages
  apt:
    name:
      - libhidapi-hidraw0
    state: present


- name: copy pre-compiled wheels
  synchronize:
    src: wheels/
    dest: /usr/local/wheels/
    rsync_opts:
      - '--include=*.whl'
      - '--exclude=*'

- name: install psychopy_session_webserver
  become_user: zaci
  become: yes
  pip:
    extra_args: --upgrade -f /usr/local/wheels
    name:
      - pip
      - psychopy==2024.1.4
      - unil-pellet-dispenser
      - psychopy-zaci
      - git+https://github.com/atuleu/zaci#egg=psychopy-session-webserver&subdirectory=psychopy-session-webserver

    virtualenv: /home/zaci/psychopy/venv
    virtualenv_command: /home/zaci/.pyenv/shims/python -m venv
