---
- name: ensure rpi-eeprom package
  apt:
    name:
      - rpi-eeprom
    state: present

- name: ensure nvme is enabled
  lineinfile:
    path: /boot/firmware/config.txt
    insertafter: "^\\[all\\]"
    line: "dtparam=nvme"
  notify: reboot for config.txt

- name: copy config file
  copy:
    src: eeprom.cfg
    dest: /var/lib/eeprom-wanted.cfg

- name: get current eeprom config
  shell: rpi-eeprom-config -o /var/lib/eeprom-current.cfg

- name: get wanted checksum
  stat:
    path: /var/lib/eeprom-wanted.cfg
    get_checksum: yes
  register: wanted

- name: get current checksum
  stat:
    path: /var/lib/eeprom-current.cfg
    get_checksum: yes
  register: current

- name: set current config
  shell: rpi-eeprom-config --apply /var/lib/eeprom-wanted.cfg
  when: wanted.stat.checksum != current.stat.checksum
  notify: reboot for config.txt

- name: ensure root is on nvme
  block:
    - name: clone rpi-clone from Jeff Gerling's repo
      git:
        repo: https://github.com/geerlingguy/rpi-clone.git
        dest: /usr/local/src/rpi-clone

    - name: installs rpi-clone
      file:
        src: "/usr/local/src/{{ item }}"
        dest: "/usr/local/sbin/{{ item }}"
        remote_src: true
      with_items:
        - rpi-clone
        - rpi-clone-setup

    - name: clone the boot partition
      shell: rpi-clone -U /dev/nvme0n1

    - name: reboot system
      reboot:

  when: boot_partition != '/dev/nvme0n1p2'
