services:
  svelte:
    image: svelte
    build: ./
    container_name: svelte
    network_mode: "host"
    environment:
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
      - DEBUG=1
    restart: 'unless-stopped'


  traefik:
    image: traefik:latest
    command:
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --accesslog=false
      - --api.insecure=true
      - --providers.file.filename=/routes.yml
    ports:
      - "80:80"
      - "8080:8080"
    extra_hosts:
      - "zaci-localhost:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./routes.yml:/routes.yml
    restart: 'unless-stopped'
